name: CI

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java_version: [8, 11, 17]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ matrix.java_version }}-gradle-${{ hashFiles('**/*.gradle*') }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run JMH
      run: ./gradlew jmh

